### PR TITLE
Added url shortener to task list

### LINKED ISSUE #98: URL Shortener with GUI
It would be good if assistant could open a url shortener GUI with a copy feature. User can make any url short using this GUI and can also copy the shorten url with a click of button.

### PR DESCRIPTION
**Pull request by pranabprohit**
## Related Issuse or bug
  -Url Shortener GUI with copy feature

Fixes: #98 

#### Describe the changes you've made
Added URL Shortener to task list with a proper GUI and a copy button to copy the shorten url.

## How Has This Been Tested?
It has been self tested by me locally.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by pranabprohit** [comment]
@Ash515 is there any issue in this PR. Should i again open a proper PR?

**Comment by Ash515** [comment]
yes this PR having some conflicts file please check it

**Comment by pranabprohit** [comment]
> yes this PR having some conflicts file please check it

Okk I will try to resolve or will make a new PR for this issue

**Comment by Ash515** [comment]
Sure make it

**Pull request closed without merging**
